plant = [ 'poppy_and_red', 'leaf_of_poppy', 'thorny_poppy', 'poppey_head', 'field_poppy', 'flower_of_poppy', 'poppy_dry', 'white_poppy', 'wander_poppy', 'seed_poppy', 'poppy_head', 'prickly_poppy','resemble_poppy', 'poppy_cold', 'seed_of_poppy', 'leaf_of_the_poppy', 'name_poppy', 'garden_poppy', 'poppy_seed', 'double_poppy', 'poppy_red', 'white_poppey', 'thornye_poppy', 'poppy_root', 'crown_of_poppy', 'sort_of_poppy', 'poppy_white', 'poppy_and_the_white', 'poppy_the_description', 'flower_of_the_poppy', 'top_of_poppy', 'red_poppy', 'seed_of_poppey', 'black_poppy', 'poppy_long', 'poppy_the_leaf', 'horn_poppy', 'poppy_grow', 'wild_poppy', 'poppy_corn', 'green_poppy', 'poppy_the_seed', 'head_of_poppy', 'tall_poppy', 'big_poppy', 'kind_of_poppy', 'poppy_the_garden', 'poppy_leave', 'poppy_and_black', 'poppy_flower', 'corn_poppy', 'poppy_sed', 'spatle_poppy']

maleGeneral = ['sir_of_poppy', 'poppy_their', 'poppy_who', 'laudanum_you', 'syr_of_poppy', 'his_laudanum', 'poppy_you']

female = ['poppy_she']

region = ['opium_of_cambaia', 'opium_turkey', 'english_poppy', 'french_poppy']

otherPlants = ['myrrh_laudanum', 'laudanum_with_rose', 'laudanum_frankincense', 'opium_nitre', 'poppy_mandrake', 'laudanum_and_wax', 'poppy_lettuce', 'violet_and_poppy', 'laudanum_aloe', 'laudanum_mastic', 'opium_and_saffron', 'quince_poppy', 'opium_saffron', 'laudanum_myrrh', 'mastic_laudanum', 'opium_and_nitre', 'hemlock_poppy', 'waterlilly_poppy', 'poppy_and_purslane', 'frankincense_opium', 'succory_poppy', 'lettuce_poppy', 'poppy_henbane', 'laudanum_rosin', 'poppy_houseleek', 'triphera_without_opium', 'laudanum_and_horehound', 'poppy_quince', 'laudanum_and_benzoin', 'opium_bevercod', 'poppy_of_rose', 'sandaraca_laudanum', 'saffron_opium', 'opium_mandrake', 'opium_hemlock', 'fig_and_poppy', 'laudanum_benjamin', 'aloe_laudanum', 'opium_henbane', 'gum_laudanum', 'henbane_opium', 'violet_poppy', 'violet_of_poppy', 'benzoine_laudanum', 'frankincense_laudanum', 'poppy_of_lettuce', 'saffron_and_opium', 'opium_and_the_saffron', 'poppy_violet', 'garlic_and_poppy', 'poppy_myrtle', 'poppy_and_lettice', 'laudanum_storax', 'opium_mandragora', 'opium_with_wax', 'poppy_and_the_nightshade', 'laudanum_ammoniacum', 'poppy_rose', 'poppy_mallow', 'laudanum_and_mastic', 'opium_and_rose', 'oat_and_poppy']

medical = ['opium_meconium', 'opiate_paracelsi', 'give_laudanum', 'dose_of_laudanum', 'dissolve_the_laudanum', 'poppy_give', 'laudanum_pill', 'opiate_composition', 'drowsy_poppy', 'brain_opium', 'beat_poppy', 'dram_of_opium', 'opiate_lozenge', 'opium_prepare', 'drag_laudanum', 'opiate_diet', 'laudanum_paracelsi', 'prepare_opium', 'drink_poppy', 'laudanum_thicken', 'compound_opiate', 'emplaster_of_laudanum', 'tincture_of_opium', 'opium_dram', 'administer_laudanum', 'opiate_with_the_syrup', 'opium_sleep', 'opiate_medicine', 'opium_extract', 'pill_of_laudanum', 'opiate_liquid', 'dram_laudanum', 'poppy_burn', 'syrup_of_poppy', 'decoction_of_poppy', 'poppy_anoint', 'dram_opium', 'drink_opium', 'opiate_electuary', 'poppy_syrup', 'give_opiate', 'poppy_of_the_decoction','laudanum_red', 'bear_laudanum', 'laudanum_warm', 'opium_cold', 'spirit_opiate','opium_camfere','castoreum_laudanum','because_opium', 'poppy_because']

generalUsage = ['follow_opiate', 'smell_of_opium', 'milk_of_poppy', 'opium_lay', 'poppy_juice', 'poppy_juyce', 'poppey_juyce', 'oil_of_poppy', 'poppy_oil', 'oil_of_poppey', 'poppy_with_oil', 'poppy_and_apply', 'gather_of_laudanum', 'use_of_laudanum', 'opium_use', 'call_opium', 'water_of_poppy', 'poppy_the_juice', 'use_of_opium', 'custom_for_opium', 'poppy_sow', 'opiate_make', 'form_of_opiate', 'poppy_have', 'perfume_of_laudanum', 'inward_opiate', 'earth_and_opium', 'serve_for_opium', 'poppy_and_little', 'use_laudanum', 'poppy_join', 'take_laudanum', 'poppy_cause', 'opiate_have', 'laudanum_say', 'opium_take', 'opium_inward', 'laudanum_take', 'opium_make', 'make_of_poppy', 'make_opiate', 'eat_poppy', 'laudanum_make', 'poppy_the_place', 'opiate_with_equal', 'call_laudanum', 'opium_have', 'take_opium', 'pure_laudanum', 'custom_of_the_opium', 'laudanum_have', 'opium_cast', 'cordial_opiate', 'opium_put', 'tablet_opiate', 'gather_and_poppy', 'poppy_call', 'poppy_boil', 'say_opium', 'take_opiate', 'swell_with_poppy', 'opium_consist', 'melt_the_laudanum', 'usage_of_opium', 'some_opiate', 'poppy_sod', 'poppy_take', 'opiate_confection', 'use_opium', 'take_of_opium', 'eat_opium', 'mean_of_laudanum', 'opiate_mean', 'poppy_use','opium_of_the_seed','opium_of_the_juice','kind_of_opiate','opium_the_juice','juice_of_poppy','therein_the_laudanum']

quantitative = ['opium_some', 'opium_half', 'half_opium', 'portion_of_opium', 'quantity_of_opium', 'loch_of_poppy', 'ounce_of_laudanum', 'ounce_of_opium', 'grain_of_opium', 'grain_of_laudanum', 'little_laudanum', 'laudanum_half', 'handful_poppy', 'little_opium', 'half_laudanum', 'half_poppy', 'little_opiate', 'laudanum_some', 'ounce_opium',  'ounce_laudanum', 'grain_of_poppy', 'some_opium','laudanum_twice', 'poppy_two','poppy_one',  'opium_two','three_poppy','laudanum_one','two_of_opium','laudanum_of_each', 'opium_three','first_opium','laudanum_three','poppy_of_each','opiate_three','opium_one','laudanum_two']

moral = ['opium_well', 'best_laudanum', 'opium_good', 'opiate_virtue', 'poppy_good', 'opiate_divinity', 'subordinates_opium', 'good_opium','virtue_of_laudanum', 'deadly_poppy', 'scruple_laudanum', 'poison_with_opium', 'poppy_the_virtue', 'bastard_poppy', 'best_opium', 'opium_of_evil']

qualitative = ['true_laudanum', 'poppy_simple', 'much_opium', 'true_opium', 'clean_laudanum', 'poppy_much', 'crude_opium', 'frothy_poppy', 'more_of_poppy', 'opium_more', 'poppy_must', 'opium_much', 'against_opium', 'opiate_against']

misc = ['laudanum_that', 'opium_than', 'than_poppy', 'than_opium', 'laudanum_again', 'opium_but', 'opium_also', 'laudanum_and_such', 'foresay_opium','also_laudanum', 'like_opium', 'these_opium', 'also_poppy', 'poppy_when', 'opium_of_each', 'like_poppey', 'laudanum_may', 'poppy_like', 'opium_not', 'laudanum_not', 'opium_will', 'if_opium', 'that_opium', 'any_laudanum', 'opiate_not', 'thereof_opiate', 'poppy_without_any', 'poppy_and_therefore', 'opium_which', 'that_laudanum', 'poppy_yet', 'which_opium', 'laudanum_also', 'laudanum_and_then', 'poppey_such', 'poppy_there', 'opiate_according', 'unto_poppy', 'opium_the_same', 'poppy_if', 'opium_and_other', 'opium_may', 'poppy_this', 'opiate_shall', 'opium_of_which', 'this_opiate', 'like_poppy', 'opium_now', 'opium_its', 'opiate_but', 'poppy_aun', 'opium_and_there', 'this_poppy', 'poppy_that', 'those_poppy', 'opiate_of_which', 'that_opiate', 'opiate_there', 'opium_can', 'opium_then', 'laudanum_which', 'other_opiate', 'poppy_whereof', 'this_laudanum', 'opiate_which', 'other_poppy', 'that_of_the_poppy', 'opium_and_yet', 'than_opiate', 'even_opium', 'laudanum_and_other', 'opium_every', 'like_the_poppy', 'opiate_whereof', 'poppy_ana', 'opium_before', 'opium_unto', 'poppy_but', 'opiate_thereof', 'opium_that', 'opium_very', 'poppy_which', 'opium_other']



skip = ['opiate_opiate', 'opiate_the_opiate','opium_opium','opium_and_opiate', 'poppy_opium', 'opium_poppy','opiate_lib']
