corrections = {
    '●urad':'murad',
    'wi●h':'wish',
    'fi●st':'first', #correct these stopwords so that they are properly removed 
    'hau●':'have',
    'god●':'god',
    'm●n':'man',
    'grea●':'great',
    '●hall':'shall',
    'christ●':'christ',
    'word●':'word',
    'be●ore':'before',
    'g●d':'god',
    '●gainst':'against',
    'b●fore':'before',
    'l●sse': 'loss',
    'upo●':'upon',
    'mad●':'made',
    'c●me':'come',
    '●efore':'before',
    'tim●':'time',
    '●orth':'north',
    '●irst':'first',
    'goo●':'good',
    'whic●':'which',
    '●hou':'thou',
    '●herefore':'therefore',
    'kn●w':'know',
    'them●':'them',
    'work●':'work',
    '●hough':'though',
    'shoul●':'should',
    '●hrist':'christ',
    'k●ng':'king',
    'other●':'others',
    'ne●er':'never',
    'rom●':'rome',
    'lord●':'lord',
    '●ither':'either',
    '●ea':'sea',
    '●ohn':'john',
    'sinne●':'sin',
    '●elfe':'self',
    '●eares':'year',
    '●rue':'true',
    'him●elfe':'himself',
    '●ayth':'say',
    '●uery':'every',
    'who●':'who',
    'hand●':'hand',
    'lif●':'life',
    'b●shop':'bishop',
    '●hus':'thus',
    '●eath':'death',
    'part●':'part',
    'place●':'place',
    'chr●st':'christ',
    '●ands':'land',
    'book●':'book',
    'jesu●':'jesus',
    'caus●':'cause',
    'woul●':'would',
    '●arth':'earth',
    'befor●':'before',
    's●lfe':'self',
    'i●sus':'jesus',
    'him●':'him',
    'act●':'act',
    'neve●':'never',
    '●ewes':'jew',
    'paul●':'paul',
    'plac●':'place',
    'up●n':'upon',
    '●nder':'under',
    'fear●':'fear',
    'go●d':'good',
    'd●ath':'death',
    '●eason':'reason',
    '●eaven':'heaven',
    'meane●':'mean',
    'o●hers':'others',
    'bishop●':'bishop',
    'mind●':'mind',
    '●uill':'evil',
    '●oules':'soul',
    'chri●●':'christ',
    'deu●':'god',
    'kin●':'kind',
    'gr●at':'great',
    'soul●':'soul',
    'eu●ry':'every',
    'speak●':'speak',
    '●orld':'world',
    '●ustice':'justice',
    'blo●d':'blood',
    'wo●ke':'work',
    'se●ke':'seek',
    '●innes':'sin',
    'n●uer':'never',
    'world●':'world',
    '●ruth':'truth',
    'we●l':'well', #most likely 'weal', which is 'well'
    'know●':'know',
    'say●':'say',
    'gre●t':'great',
    'ra●her':'rather',
    'christian●':'christian',
    'person●':'person',
    'pl●ce':'place',
    'hea●en':'heaven',
    'fa●th':'faith',
    'muc●':'much',
    'sonn●':'son',
    '●udgement':'judgement',
    'sea●':'sea',
    '●nother':'another',
    'neu●r':'never',
    'help●':'help',
    'de●th':'death',
    'c●use':'cause',
    '●de':'ode',
    's●lues':'selves',
    'mu●t':'must',
    'e●ery':'every',
    '●ect':'sect',
    'they●':'they',
    'pe●ce':'peace',
    '●lace':'place',
    'powe●':'power',
    'pop●':'pope',
    'requi●e':'require',
    'whos●':'whose',
    '●ormer':'former',
    'pope●':'pope',
    'wh●ther':'whether',
    'call●d':'call',
    'i●hn':'john',
    'spirit●':'spirit',
    'cau●e':'cause',
    '●urther':'further',
    'beh●ld':'behold',
    'good●':'goods', #double check
    'rea●on':'reason',
    'cause●':'cause',
    'di●ers':'diverse',
    'ou●r':'over',
    'f●ith':'faith',
    '●othing':'nothing',
    '●bout':'about',
    'worke●':'work',
    's●cond':'second',
    'love●':'love',
    'soule●':'soul',
    'beg●n':'begin',
    'grac●':'grace',
    'd●st':'do',
    'desi●e':'desire',
    'end●':'end',
    'need●':'need',
    'c●rist':'christ',
    'wom●n':'woman',
    'sub●ect':'subject',
    'heart●':'heart',
    'n●me':'name',
    'manne●':'manner',
    'turk●':'turk',
    '●ewe':'jew',
    'pass●':'pass',
    'unde●':'under',
    'b●cause':'because',
    'r●me':'rome',
    'firs●':'first',
    'c●lled':'call',
    'land●':'land',
    'wis●':'wise',
    'sin●e':'sin',
    'pre●ent':'present',
    'augustin●':'augustine',
    'chri●t':'christ',
    'com●ort':'comfort',
    'divin●':'divine',
    'chief●':'chief',
    'pow●r':'power',
    'm●anes':'mean',
    'wh●m':'whom',
    'reaso●':'reason',
    'g●ace':'grace',
    'hop●':'hope',
    'john●':'john',
    'less●':'less',
    'form●':'form',
    'law●':'law',
    're●son':'reason',
    'po●t':'poet',
    '●loud':'cloud',
    'so●le':'soul',
    'angel●':'angel',
    'roman●':'roman',
    'g●od':'good',
    '●athers': 'father',
    '●eace':'peace',
    'c●st':'cost',
    'da●id':'david',
    'sp●ke':'spoke',
    'ch●rch':'church',
    'tru●h':'truth',
    'name●':'name',
    'sp●rit':'spirit',
    'wi●ked':'wicked',
    'vers●':'verse',
    'heau●n':'heaven',
    'franc●':'france',
    '●ittle':'little',
    'de●end':'decend',
    'gi●en':'given',
    'h●mselfe':'himself',
    'heave●':'heaven',
    'pre●ence':'presence',
    '●onour':'honour',
    'peac●':'peace',
    'lea●t':'least',
    'qu●st':'quest',
    'fir●t':'first',
    'ne●ther':'neither',
    'spiri●':'spirit',
    'oth●rs':'others',
    'gr●ce':'grace',
    '●race':'grace',
    'con●ession':'concession',
    'fals●':'false',
    'worl●':'world',
    'town●':'town',
    '●ature':'nature',
    'w●rd':'word',
    'rathe●':'rather',
    'littl●':'little',
    'p●pe':'pope',
    'pari●':'paris',
    'f●ther':'father',
    'b●ought':'brought',
    '●icked':'wicked',
    'comm●nded':'commanded',
    'themselu●s':'themselves',
    'appear●':'appear',
    'ho●our':'honour',
    '●ortune':'fortune',
    'w●se':'wise',
    'praye●':'prayer',
    'crown●':'crown',
    'prophet●':'prophet',
    'k●ngs':'king',
    'grace●':'grace',
    'wate●':'water',
    'fait●':'faith',
    '●ourney':'journey',
    'human●':'human',
    '●ngland':'england',
    'promise●':'promise',
    'scripture●':'scripture',
    'forc●':'force',
    'e●ist':'exist',
    '●housand':'thousand',
    'christi●n':'christian',
    'drink●':'drink',
    'citi●':'city',
    'pre●ious':'precious',
    'christia●':'christian',
    'command●ment':'commandment',
    'england●':'england',
    'contra●y':'contrary',
    'theodore●':'theodore',
    'david●':'david',
    '●ealous':'jealous',
    'seruant●':'servant',
    'pro●ession':'procession',
    'gre●ke':'greek',
    'saint●':'saint',
    'cou●nant':'covenant',
    'gentlem●n':'gentlemen',
    'ad●m':'adam',
    'christ●an':'christian',
    'letter●':'letter',
    '●lory':'glory',
    'purpose●':'purpose',
    'jos●ph':'joseph',
    'pet●r':'peter',
    'souldi●rs':'soldiers',
    'a●gustine':'augustine',
    'prayer●':'prayer',
    'th●mas':'thomas',
    'sacrifice●':'sacrifice',
    '●uerlasting':'everlasting',
    '●udgements':'judgement',
    'catholik●':'catholic',
    'ser●ant':'servant',
    '●aughter':'daughter',
    'sacrific●':'sacrifice',
    'jew●s':'jew',
    'bishops●':'bishop',
    'heau●nly':'heavenly',
    'superstitio●s':'superstitious',
    'jer●salem':'jerusalem',
    'je●usalem':'jerusalem',
    # the following corrections are from the EP Tuning set of 26 files 
    'w●e': 'woe', 'w●st': 'west', 's●a': 'sea', '●rade': 'trade', 'fi●h': 'fish', 
    'ship●': 'ship', 'ke●pe': 'keep', 's●ll': 'sell', 'sp●niards': 'spaniard', 
    'u●e': 'use', 'us●': 'use', 'cap●': 'cape', 'diu●rs': 'diverse', 
    'i●land': 'island', 'paracous●y': 'paracousey', 'indian●': 'indian', 
    'spaniard●': 'spaniard', 'portugal●': 'portugal', 'co●st': 'coast', 
    'abo●rd': 'aboard', 'r●uer': 'river', 'countre●': 'country', 
    's●aves': 'slave', 'spain●': 'spain', 'englishm●n': 'englishman', 
    'leagues●': 'league', 'boa●': 'boat', 'league●': 'league', 
    '●ighest': 'highest', 'batta●le': 'battle', 'fi●lde': 'field', 
    'vo●age': 'voyage', 'couns●ll': 'counsel', '●amous': 'famous', 
    'gr●ene': 'green', 'countrey●': 'country', 'sa●led': 'sail', 
    't●wne': 'town', 'en●lish': 'english', 'south●': 'south', 'ank●red': 'anchor', 
    'river●': 'river', 'sain●': 'saint', 'fra●ce': 'france', 'boh●mia': 'bohemia', 
    'people●': 'people', 'rive●': 'river', 'ch●na': 'china', 'north●': 'north', 
    'norwegia●': 'norwegian', 'b●rbarie': 'barbary', 'spaine●': 'spain', 
    'spania●d': 'spaniard', 'inca●': 'incan', 'tartari●': 'tartary', 
    's●uage': 'savage', 'comp●ny': 'company', '●mbarked': 'embark', 
    'canari●': 'canary', 'w●men': 'woman', 'wood●': 'wood', 
    'dominio●s': 'dominion', 'guin●●': 'guinea', 'furnishe●': 'furnished', 
    'molestation●': 'molestation', 'ta●ta●ia': 'tartary', 
    'g●rmany': 'germany', 'geo●gia': 'georgia', 'law●s': 'law', 
    'merchandise●': 'merchandise', 'queene●': 'queen', 'engli●hmen': 'englishman', 
    'cott●n': 'cotton', 'angol●': 'angola', 'barga●ne': 'bargain', 
    'canaries●': 'canary', 'ven●ce': 'venice', 'merc●hants': 'merchant', 
    'merchaunt●': 'merchant', 'nigr●': 'negro', 'portuga●': 'portugal', 
    'borne●': 'borneo', 'pe●u': 'peru', 'skin●e': 'skin', 'curtes●e': 'courtesy', 
    'spani●rds': 'spaniard', 'u●scount': 'viscount', 'inhabitants●': 'inhabitant', 
    'ta●taria': 'tartary', 'edward●': 'edward', 'ru●sia': 'russia', 
    'princ●●': 'prince', 'isl●': 'isle', 'authorise●': 'authorise', 
    's●ede': 'seed', 'golde●': 'golden', 'shippe●': 'shipped', 'sunn●': 
    'sun', 'leather●': 'leather', 'turke●': 'turkey', 'plain●': 'plain', 
    'per●ian': 'persian', 'jenkin●on': 'jenkinson', 'excha●ges': 'exchange', 
    'necess●tie': 'necessity', 'per●●an': 'persian', 'barbar●●s': 'barbarous', 
    'je●uites': 'jesuit', 'domi●ions': 'dominion', 'in●erecession': 'intercession', 
    'jenkinson●': 'jenkinson', 'ea●●erly': 'eagerly', 'venic●': 'venice', 
    'indie●': 'indies', 'forbidden●': 'forbidden', 'plimmouth●': 'plymouth', 
    'peru●': 'peru', 'ta●tar': 'tartar', 'emperour●': 'emperor', 
    'treasure●': 'treasure', 'tak●n': 'taken', 'magellan●': 'magellan', 
    'victuals●': 'victual', 'ri●h': 'rich', 'm●rcator': 'mercator', 
    'grain●': 'grain', 'squemishly●': 'squeamishly', 'sib●ria': 'siberia', 
    'wands●': 'wand', 'in●a': 'inca', 'mountaines●●●': 'mountain', 
    'commodi●es': 'commodity', 'company●': 'company', 'magog●': 'magog',
    'a●tracan': 'astracan', 's●iling': 'sailing', 'boat●': 'boat',
    'consul●': 'consul', 'v●nice': 'venice', 'mines●': 'mine', 
    'naple●': 'naples', 'tartar●': 'tartary', 'tartar●●': 'tartary', 
    'riche●': 'riches', 'engla●d': 'england', '●ou●neys': 'journey', 
    'island●': 'island', 's●rue': 'serve', 'deceive●': 'deceive', 
    'ru●●ia': 'russia', 'h●●panis': 'hispanus', 'commande●': 'commander', 
    'wes●': 'west', 'master●': 'master', '●sland': 'island', 'gre●ce': 'greece', 
    'di●●covered': 'discovered', 'france●': 'france', '●nglish': 'english', 
    'b●lgaria': 'bulgaria', 'stones●': 'stone', 'forcibl●': 'forcible', 
    'flood●': 'flood', 'phisi●ians': 'physician', 'f●orentia': 'florentia', 
    'trinidad●': 'trinidad', 'monte●': 'monte', 'ri●ers': 'river', 
    '●urnished': 'furnish', 'ar●est': 'arrest', 'o●ientali': 'oriental', 
    'indi●●': 'indies', 'grai●s': 'grain', '●ortugals': 'portugal', 
    'f●llow': 'follow', 'gui●nians': 'guianian', 'cape●': 'cape', 
    'georgia●': 'georgia', 'swed●n': 'sweden', 'arabi●●': 'arabia', 
    'q●eenes': 'queen', 'town●s': 'town', 'infinit●': 'infinity', 
    'i●on': 'iron', 'po●tugals': 'portugal', 'bett●r': 'better', 
    'jud●cious': 'judicious', 'portugall●': 'portugal', 'russ●n': 'russian', 
    'h●ngaria': 'hungary', 'tu●ke': 'turk', 'fru●●ion': 'fruition', 
    'harbo●●': 'harbor', 'histo●●●': 'history', 'chin●': 'china', 
    'discou●red': 'discover', 'fre●': 'free', 's●ruants': 'servant', 
    '●paine': 'spain', 'giu●n': 'give', 'sp●●iards': 'spaniard', 
    'franciscu●': 'franciscus', 'savage●': 'savage', '●lorence': 'florence', 
    'nichola●': 'nicholas', 'water●': 'water', 'damascu●': 'damascus', 
    'naked●': 'naked', '●mpire': 'empire', 'persi●': 'persia', 
    'ta●tarorum': 'tartar', 'sl●ues': 'slave', 'russiae●': 'russia', 
    'warr●●': 'war', 'nicho●as': 'nicholas', 'ja●a': 'java', 
    'scotland●': 'scotland', 'no●uagians': 'norweigian', 
    'portugallie●': 'portugal', 'r●uers': 'river', 'jo●dan': 'jordan', 
    '●ountries': 'country', 'fishe●': 'fish', 'honourable●': 'honourable', 
    '●ruit': 'fruit', '●eagues': 'league', 'unpeopled●': 'unpeopled', 
    'royal●': 'royal', 'aeth●opia': 'ethiopia', 'pla●ted': 'plant', 
    'pr●mise': 'promise', 'shipp●': 'ship', '●ufficient': 'sufficient', 
    'take●': 'take', 'bulga●ia': 'bulgaria', 'gold●': 'gold', 'jame●': 'james', 
    'g●rmanie': 'germany', 'noblem●n': 'nobleman', 'russi●': 'russia', 
    'ordinances●': 'ordinance', 'cast●le': 'castile', 'go●ds': 'good', 
    'hispani●la': 'hispaniola', '●mbassadour': 'ambassadour', 
    '●urnish': 'furnish', 'jap●n': 'japan', 'engli●hman': 'englishman',
    'woo●s': 'wood', 'joh●': 'john', 'portug●ls': 'portugal', 
    '●amine': 'famine', 'informed●': 'inform', 'authorit●e': 'authority', 
    'india●s': 'indian', 'tartar●ights': 'tartar', 'paradis●': 'paradise', 
    'flo●d': 'flood', 'span●ards': 'spaniard', 'gentlemen●': 'gentleman', 
    'prussians●': 'prussian', 'af●ica': 'africa', 'diver●': 'diverse', 
    'idol●': 'idol', 'cosmopoli●es': 'cosmopolity', 'hungari●': 'hungary', 
    '●ames': 'james', '●hina': 'china', 'w●rlde': 'world', 'clo●h': 'cloth', 
    'nig●o': 'negro', 'and●ew': 'andrew', 'eliz●beth': 'elizabeth', 
    'earth●': 'earth', 'consta●tinople': 'constantinople', 'cath●ya': 'cataya', 
    'for●es': 'forces', 'englishmen●': 'englishman', 'constan●inople': 'constantinople',
    'na●ion': 'nation', 'londo●': 'london', 'china●': 'china', 'souldiers●': 'soldier', 
    '●ich': 'rich', 'complain●●': 'complain', 'portinga●s': 'portingal', 
    'portingals●': 'portingal'
}

lemmas = {
    # the following are for key entities 
    'fravncis':'francis','frauncis':'francis','frances':'francis',
    'iohn':'john','couel':'covel','anthonie':'anthony', 
    'ienkinson':'jenkinson','iessey':'jessey','jesseys':'jessey',
    'heylyns':'heylyn','tradescants':'tradescant','harcovrt':'harcourt',
    'iean':'jean','wroth':'wrothe', 'hvmphrey':'humphrey', 
    'humfrey':'humphrey', 'humphrie':'humphrey', 'humfry':'humphrey', 
    'gilberts':'gilbert', 'edwarde':'edward', 
    'bartholmew':'bartholomew', 'smyth':'smith', 'smythe':'smith', 'smithes':'smith', 
    'smiths':'smith', 'doddridge':'dodderidge', 'colvmbvs':'columbus', 
    'edwyn':'edwin', 'stapers':'staper', 'ihon':'john', 'gosnoll':'gosnold',
    'turkie':'turkey','turky':'turkey','companie':'company','leuant':'levant',
    'easte':'east',

    #the following are based on the most commonly occuring words in 1580-1641 texts 
    'cor.':'corinthian',
    'psal':'psalm',
    'brethren':'brother', #check
    'luk':'luke',
    'yea':'yes',
    'betwixt':'between',
    'vers':'verse',
    'joh':'john',
    'quoth':'quote',
    'beseech':'beg',
    'belove':'beloved',
    'origen':'origin',
    'presbyter':'presbyterian',
    'apostolical':'apostolic',
    'castille':'castile',
    'mahomet':'muhammad', #6k mentions 
    'matt':'matthew',
    'juda':'judah',
    'chrysostome':'chrysostom',
    'psa':'psalm',
    'answ':'answer',
    'rev':'reverand',
    'carcase':'carcass',
    'antiochus':'antioch',
    'environ':'environment',
    'signior':'signor',
    'arragon':'aragon',
    'serm':'sermon',
    'corinth':'corinthian',
    'reuel':'revelation',
    'bassa':'pasha', #bashaw is earlier form of Turkish title 'pasha'
    'esq':'esquire',
    'innocency':'innocence',
    'jerem':'jeremiah',
    'augustin':'augustine',
    'obstinancy':'obstinance',
    'heirom':'heirome',
    'virgilius':'virgil', #i really want to use vergil instead 
    'vergilius':'virgil',
    'vergil':'virgil',
    'tully':'cicero', #love this name 
    'maior':'major',
    'snake':'serpent',
    'josua':'joshua',
    'authentical':'authentic',
    'laurence':'lawrence',
    'macedon':'macedonia',
    'chirurgeon':'surgeon',
    'caius':'gaius',
    'britan':'britain',
    'unskilful':'unskillful',
    'evangelicall':'evangelical',
    'joane':'joanne',
    'embassage':'embassy',
    'christen':'christian',
    'eccles.':'ecclesiastes',
    'hist.':'history',
    'mar.':'mark',
    'mariner':'sailor',
    'jam.':'james', #unsure
    'epist':'epistle', #unsure
    'apoc.':'apocrypha',
    'art.':'article',
    'elias':'elijah',
    'hom.':'homily',
    'januarie':'january',
    'greecian':'grecian',
    'curran':'currant',
    'pengwin':'penguin',
    'pinnasses':'pinnace',
    'cananor':'kannur',
    'straits':'strait',
    'yeraslave':'yaroslavl',
    'cantar':'kantar',
    'maronites':'maronite',
    'bellarmin':'bellarmine',
    'bishopricke':'bishopric',
    'dominicke':'dominic',
    'majestical':'majestic',
    'catholics':'catholic',
    'isaak':'isaac',
    'monastical':'monastic',
    'fol.':'folio',
    'quest.':'quest',
    'ca.':'circa',
    'jer.':'jeremiah',
    'phil.':'philipp',
    'travail':'travel',
    'sith':'since',
    'answ':'answer',
    'epist.':'epistle',
    'romish':'roman',
    'lesser':'less',
    'clothes':'cloth',
    'wilful':'willfull',
    'col.':'column',
    'eph.':'ephesians',
    'offering':'offer',
    'flatter':'flat',
    'luc.':'luke',
    'ephes':'ephesian',
    'chron.':'chronicle',
    'num.':'number',
    'tom.':'tomorrow',
    'eccles.':'ecclesiastical',
    'commonalty':'commonality',
    'histor':'history',
    'jerom':'jerome',
    'josias':'josiah',
    'zacharie':'zachary',
    'enquiry':'inquiry',
    'sicilia':'sicily',
    'tragical':'tragic',
    'wilfulness':'willfulness',
    'caluinist':'calvinist',
    'entrails':'entrail',
    'sepulcher':'sepulchre',
    'flaunders':'flanders',
    'bourgongne':'bourguignon',
    'ambassage':'embassy',
    'aethiopian':'ethiopian',
    'chrisostome':'chrysostom',
    'orthodoxal':'orthodox',
    'praedict':'predict',
    'jehova':'jehovah',
    'caluine':'calvin',
    'ingrateful':'ungrateful',
    'tyme':'time',
    'ingraft':'engraft',
    'judaea':'judea',
    'impotency':'impotence',
    'grecia':'greece',
    'impatiency':'impatience',
    'josuah':'joshua',
    # the following are corrections based on our key terms list as well as the EP Tuning set of 26 files 
    'commodities':'commodity',
    'trades':'trade',
    'colonies':'colony',
    'planters':'planter',
    'plantations':'plantation',
    'gods':'god',
    'adventurers':'adventurer',
    'aduenturers':'adventurer',
    'aduenturer':'adventurer',
    'aduenture':'adventure',
    'merchandizing':'merchandise',
    'profits':'profit',
    'drinking':'drink',
    'currans':'currant',
    'pipes':'pipe',
    'beavers':'beaver',
    'bever':'beaver',
    'furres':'fur',
    'adventures':'adventure',
    'passages':'passage',
    'pearls':'pearl',
    'perles':'pearl',
    'fantasia':'fantasy',
    'silke':'silk',
    'silkeworms':'silkworm',
    'whales':'whale',
    'islands':'island',
    'spices':'spice',
    'consuming':'consume',
    'consumptions':'consumption',
    'corrants':'currant',
    'carpets':'carpet',
    'importations':'importation',
    'exportations':'exportation',
    'raisins':'raisin',
    'clothes':'cloth',
    'infidels':'infidel',
    'pirates':'pirate',
    'barbarians':'barbarian',
    'shippes':'ship',
    'ships':'ship',
    'shipwrecks':'shipwreck',
    'miscarriages':'miscarriage',
    'rapines':'rapine',
    'moores':'moor',
    'moors':'moor',
    'deputie':'deputy',
    'agents':'agent',
    'pagans':'pagan',
    'joynt stock':'jointstock',
    'joynt-stock':'jointstock',
    'jointstock':'jointstock',
    'trading':'trade',
    'traffique':'traffic',
    'trafficke':'traffic',
    'companies':'company',
    'merchants':'merchant',
    'merchaunts':'merchant',
    'governments':'government',
    'politique':'politic',
    'slaves':'slave',
    'negroes':'negro',
    'negros':'negro',
    'captives':'captive',
    'novelties':'novelty',
    'exchanging':'exchange', #exchange can be noun and verb
    'exchanges':'exchange',
    'bartering':'barter',
    'drugges':'drug',
    'drugs':'drug',
    'dyes':'dye',
    'cochinele':'cochineal',
    'encouragements':'encouragement',
    'encouraging':'encourage', #maybe encourage?
    'planting':'plant',
    'enterprises':'enterprise',
    'nations':'nation',
    'seeds':'seed',
    'motives':'motive',
    'monarchies':'monarchy',
    'virtues':'virtue',
    'territories':'territory',
    'discoveries':'discovery',
    'rivers':'river',
    'riuers':'river',
    'riuer':'river',
    'diuers':'diverse',
    'divers':'diverse',
    'diuerse':'diverse',
    'discouery':'discovery',
    'utilities':'utility',
    'beliefs':'belief',
    'countries':'country',
    'souls':'soul',
    'bodies':'body',
    'inlargement':'enlargement',
    'abilities':'ability',
    'successes':'success',
    'wives':'wife',
    'savages':'savage',
    'sauages':'savage',
    'sauage':'savage',
    'beasts':'beast',
    'devils':'devil',
    'deuils':'devil',
    'deuil':'devil',
    'evils':'evil', 
    'euil':'evil',
    'inhabitants':'inhabitant',
    'monies':'money',
    'monys':'money',
    'mony':'money',
    'moneys':'money',
    'conversions':'conversion',
    'countrie':'country',
    'mothercountrie':'mothercountry',
    'commonweal':'commonwealth',
    'commonweale':'commonwealth',
    'monarchesse':'monarchess',
    'servants':'servant',
    'seruant':'servant',
    'seruants':'servant',
    'drinks':'drink',
    'histories':'history',
    'penuries':'penury',
    'men':'man',
    'women':'woman',
    'complaints':'complaint',
    'slothfulness':'sloth',
    'monopolies':'monopoly',
    'monopolising':'monopoly',
    'monopolise':'monopoly',
    'isles':'isle',
    'islands':'island',
    'harbours':'harbour',
    'caimpainge':'campaign',
    'waters':'water',
    'lords':'lord',
    'warre':'war',
    'warres':'war',
    'wars':'war',
    'speculations':'speculation',
    'observations':'observation',
    'travellers':'traveller',
    'travails':'travel',
    'travailler':'traveller',
    'virgins':'virgin',
    'deaths':'death',
    'provinces':'province',
    'forraine':'foreign',
    'forraigne':'foreign',
    'aduancement':'advancement',
    'expectations':'expectation',
    'difficulties':'difficulty',
    'enemies':'enemy',
    'travail':'travel',
    'lawfull':'lawful',
    'lawfvll':'lawful',
    'unlawfull':'unlawful',
    'vnlawfvll':'unlawful',
    'vnlawfull':'unlawful',
    'enuie':'envy',
    'yron':'iron',
    'inuasion':'invasion',
    'invading':'invade',
    'industriousness':'industrious',
    'sunne':'sun',
    'sonne':'son',
    'sunnes':'sun',
    'sons':'son',
    'fishes':'fish',
    'horses':'horse',
    'journeys':'journey',
    'cochinill':'cochineal',
    'idolatrie':'idolatry',
    'humours':'humour',
    'scarcitie':'scarcity',
    'terrors':'terror',
    'uiceroy':'viceroy',
    'embassage':'embassy',
    'seaman':'sailor',
    'seamen':'sailor',
    'murderer':'murder',
    'uiceadmirall':'viceadmiral',
    'protestants':'protestant',
    'heathens':'heathen',
    'lawyers':'lawyer',
    'chirurgeon':'surgeon',
    'maior':'major',
    'principalities':'principality',
    'restauration':'restoration',
    'englishmen':'englishman',
    'uine':'vine',
    'colonia':'colony',
    'episcopi':'episcopate',
    'elizabetha':'elizabeth',
    'sultana':'sultan',
    'cochinilla':'cochineal',
    'erterprise':'enterprise',
    'reg.':'regina',
    'esa.':'isaiah',
    'dan.':'daniel',
    'divers':'diverse',
    
    # the following are lemmas from the EP Tuning set of 26 texts 
    'raleghs': 'ralegh', 'raliana': 'raleana', 'bereo': 'berreo', 'smythe': 'smith', 
    'bargraue': 'bargrave', 'henrie': 'henry', 'magelane': 'magellan', 
    'christendome': 'christendom', 'plymmouth': 'plymouth', 'japon': 'japan', 
    'trinidado': 'trinidad', 'begala': 'belgium', 'soliman': 'suleiman', 
    'constantinop': 'constantinople', 
    # 'anatolia': 'turkey',  #double check 
    'guiana': 'guyana', 'bengala': 'bengal', 'cartagena': 'carthage', 
    'britannia': 'britain', 'mogoll': 'mughal', 'iews': 'jew', 'iesuites': 'jesuit', 
    'somers': 'bermuda', 'aethiopia': 'ethopia', 'aegypt': 'egypt', 
    'grecian': 'greek', 'mahumetanisme': 'islam', 'geographic': 'geography', 
    'seylon': 'ceylon', 'armenians': 'armenian', 'tunis': 'tunisia', 
    'flores': 'flower', 'cambaya': 'cambaye', 'valentia': 'valencia', 
    'priaman': 'pariaman', 'vologda': 'volga', 'jaquatra': 'jakarta', 
    'antiochia': 'antioch', 'mesina': 'messina', 'moscovie': 'moscow', 
    'castille': 'castile', 'carthage': 'carthagena', 'polonia': 'poland', 
    'malaca': 'malacca', 'manhumetans': 'muhammadan', 'dominicke': 'dominica', 
    'lahor': 'lahore', 'canaria': 'canary', 'piru': 'peru', 'alger': 'algiers', 
    'macedon': 'macedonia', 'mecha': 'mecca', 'christani': 'christian', 
    'japonian': 'japanese', 'chinese': 'chinois', 'russ': 'russia', 
    'genovese': 'genoese', 'flander': 'flanders', 'scandia': 'scandinavia', 
    'soltan': 'sultan', 'phaenicians': 'phoenician', 'josua': 'joshua', 
    'turkeman': 'turk', 'creta': 'crete', 'transilvania': 'transylvania', 
    'irland': 'ireland', 'brandenbourg': 'brandenburg',
    'abram':'abraham','bisphoriches':'bishopric','brasill':'brazil',
    'brasilia':'brazil','brasilian':'brazilian','brasil':'brazil',
    'brasile':'brazil','cannada':'canada','chineses':'chinese',
    'germani':'germany','germanie':'germany','germanye':'germany',
    'germanyes':'germany','corea':'korea','corean':'korean','rvssia':'russia',
    'prvssia':'prussia','prussians':'prussian','barselona':'barcelona',
    'spaniards':'spaniard','spaniardes':'spaniard','spaniarde':'spaniard',
    'spanyard':'spaniard','spanyardes':'spaniard','spanyards':'spaniard',
    'venitians':'venetian','venitian':'venetion','venetia':'venice',
    'venisia':'venice','mahumet':'muhammad','mohammad':'muhammad',
    'mohometans':'muhammadan','muhametan':'muhammadan','mohmetan':'muhammad',
    'muhametans':'muhammadan','mahometan':'muhammadan','mahometans':'muhammadan',
    'poperie':'popery','papish':'popish','papistry':'popery','papistrie':'popery'
}
